## Introduction to Scikit-Learn (sklearn)
This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:

# 🧠 Scikit-Learn Workflow

## 📌 What We're Covering

1. **An end-to-end Scikit-Learn workflow**
2. **Getting the data ready**
3. **Choose the right estimator/algorithm for our problem**
4. **Fit the model/algorithm and use it to make predictions on our data**
5. **Evaluating a model**
6. **Improve a model**
7. **Save and load a trained model**
8. **Putting it all together!**

In [1]:
# 1. Get the data ready

import pandas as pd

heart_disease = pd.read_csv('heart-disease.csv')

heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
# Create X (features matrix) 

X = heart_disease.drop('target',axis=1)

# Creates y (labels)

Y = heart_disease['target']

In [3]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [4]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [5]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (3.6.0)

In [6]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the model
clf = RandomForestClassifier(n_estimators=100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
# 3. Fit the model to the training data

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.2)

In [8]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [9]:
import numpy as np

In [10]:
y_label = clf.predict(np.array([1,6,4,9,7]))

C:\Users\rajvi\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[1. 6. 4. 9. 7.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
y_preds = clf.predict(x_test)

In [12]:
y_preds

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1])

In [13]:
y_test

9      1
198    0
127    1
53     1
121    1
      ..
241    0
170    0
169    0
65     1
144    1
Name: target, Length: 61, dtype: int64

In [14]:
y_train

159    1
297    0
291    0
148    1
142    1
      ..
64     1
236    0
115    1
298    0
140    1
Name: target, Length: 242, dtype: int64

In [15]:
# 4. Evaluate the model on the training data and test data

clf.score(x_train,y_train)

1.0

In [16]:
clf.score(x_test,y_test)

0.7377049180327869

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.86      0.58      0.69        31
           1       0.68      0.90      0.77        30

    accuracy                           0.74        61
   macro avg       0.77      0.74      0.73        61
weighted avg       0.77      0.74      0.73        61

In [18]:
confusion_matrix(y_test,y_preds)

array([[18, 13],
       [ 3, 27]])

In [19]:
accuracy_score(y_test,y_preds)

0.7377049180327869

In [20]:
# 5. Improve a model
# Try different amount of n_estimators
np.random.seed(42)

for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train, y_train)  # Train the model
    
    print(f"Model accuracy on test set: {clf.score(x_test, y_test) * 100:.2f}%")
    print("-" * 50)

Trying model with 10 estimators...
Model accuracy on test set: 80.33%
--------------------------------------------------
Trying model with 20 estimators...
Model accuracy on test set: 77.05%
--------------------------------------------------
Trying model with 30 estimators...
Model accuracy on test set: 80.33%
--------------------------------------------------
Trying model with 40 estimators...
Model accuracy on test set: 75.41%
--------------------------------------------------
Trying model with 50 estimators...
Model accuracy on test set: 77.05%
--------------------------------------------------
Trying model with 60 estimators...
Model accuracy on test set: 75.41%
--------------------------------------------------
Trying model with 70 estimators...
Model accuracy on test set: 75.41%
--------------------------------------------------
Trying model with 80 estimators...
Model accuracy on test set: 72.13%
--------------------------------------------------
Trying model with 90 estimators...
Model accuracy on test set: 73.77%
--------------------------------------------------

In [21]:
# 6. Save a model and load it

import pickle

pickle.dump(clf,open('random_forest_model_1.pkl','wb'))

In [22]:
loaded_model = pickle.load(open('random_forest_model_1.pkl','rb'))

loaded_model.score(x_test,y_test)

0.7377049180327869